[build]
builder = "railpack"
buildCommand = "pip install -r requirements.txt"

# Cài thêm các thư viện hệ thống cần thiết cho OpenCV và Poppler
aptPackages = [
  "libgl1",
  "libglib2.0-0",
  "poppler-utils"
]

[deploy]
startCommand = "python bot.py"
