[build]
builder = "Nixpacks"

[build.nixpacksPlan]
phases.setup.aptPkgs = ["libgl1", "libglib2.0-0", "poppler-utils"]
phases.install.cmds = ["pip install -r requirements.txt"]
start = "python bot.py"
