[build]
builder = "railpack/python"

# Cài thêm các thư viện hệ thống cần thiết cho OpenCV và PDF xử lý
apt_packages = [
  "libgl1",
  "libglib2.0-0",
  "poppler-utils"
]

[deploy]
start = "python bot.py"
